domain: capro.xy2z.io
url: https://capro.xy2z.io
locale: en_US
version: 1.11 # used to bump assets versions to clear caching.

links:
  github:
    title: GitHub
    url: 'https://github.com/xy2z/capro'

  community:
    title: Community
    url: 'https://github.com/xy2z/capro/discussions'
